# PyTorch Tutorial 01. PyTorch vs. NumPy

- 基本的に，[このチュートリアル](https://tutorials.pytorch.kr/beginner/deep_learning_60min_blitz.html)の内容に基づいている．  
- ある程度のPython+科学技術計算経験者が早く把握のできるようにちょっと加えてみた．  
- GPU関連の操作は，恐らく複数GPUを使わない限り実感が沸かないと判断し，除外している．  
- 全体として，**PyTorchはNumpy機能を代替している**と要約できる．  

In [1]:
from __future__ import print_function
import torch

import numpy as np ## NumPy as comparison target

## データ構造

PyTorchのテンソルは，基本的にNumPyの行列と思えば良い．

In [2]:
## declare container with random values
x_pt = torch.rand(5, 3)
print(x_pt)

x_np = np.random.rand(5, 3)
print(x_np)

tensor([[0.2602, 0.5925, 0.2110],
        [0.2940, 0.4043, 0.2569],
        [0.1033, 0.0964, 0.2389],
        [0.4379, 0.6319, 0.8611],
        [0.0877, 0.9227, 0.8046]])
[[0.85146844 0.76726657 0.77656729]
 [0.5854232  0.26934039 0.19205566]
 [0.99524037 0.87030753 0.92522028]
 [0.63730814 0.93278414 0.0784962 ]
 [0.2918383  0.05876011 0.68389239]]


In [3]:
## conversion from list (already existing data)
x = [5.5, 3.0]

x_pt = torch.tensor(x)
print(x_pt)

x_np = np.array(x)
print(x_np)

tensor([5.5000, 3.0000])
[5.5 3. ]


In [4]:
## declare zero-cleared container
x_pt = torch.zeros(5, 3, dtype=torch.long)
print(x_pt)

x_np = np.zeros([5, 3], dtype=np.long)
print(x_np)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
## 大きさ表示
print(x_pt.size())
print(x_np.shape)

torch.Size([5, 3])
(5, 3)


## 演算

- 基本的に，NumPyで行われた多数の演算を無理なくPyTorchで出来るのを示している．
- 複数GPUを扱う際の処理が若干気になるが，恐らくチュートリアルでやる内容でないのでこれで良いか．

In [6]:
## (1) Python operator (2) library's operator
y_pt = torch.rand(5, 3)
print(x_pt + y_pt)
print(torch.add(x_pt, y_pt))

y_np = np.random.rand(5, 3)
print(x_np + y_np)
print(np.add(x_np, y_np))

tensor([[0.9669, 0.4496, 0.3255],
        [0.2800, 0.9695, 0.9033],
        [0.8509, 0.9402, 0.0901],
        [0.0302, 0.4726, 0.2825],
        [0.6208, 0.3520, 0.2769]])
tensor([[0.9669, 0.4496, 0.3255],
        [0.2800, 0.9695, 0.9033],
        [0.8509, 0.9402, 0.0901],
        [0.0302, 0.4726, 0.2825],
        [0.6208, 0.3520, 0.2769]])
[[0.81128594 0.7028886  0.27452661]
 [0.52781861 0.10260228 0.79066118]
 [0.18547738 0.91515995 0.42936008]
 [0.80653872 0.91546415 0.93381   ]
 [0.61623963 0.35674746 0.15297064]]
[[0.81128594 0.7028886  0.27452661]
 [0.52781861 0.10260228 0.79066118]
 [0.18547738 0.91515995 0.42936008]
 [0.80653872 0.91546415 0.93381   ]
 [0.61623963 0.35674746 0.15297064]]


In [7]:
## use "out" argument
result_pt = torch.empty(5, 3)
torch.add(x_pt, y_pt, out=result_pt)
print(result_pt)

result_np = np.empty([5, 3])
np.add(x_np, y_np, out=result_np)
print(result_np)

tensor([[0.9669, 0.4496, 0.3255],
        [0.2800, 0.9695, 0.9033],
        [0.8509, 0.9402, 0.0901],
        [0.0302, 0.4726, 0.2825],
        [0.6208, 0.3520, 0.2769]])
[[0.81128594 0.7028886  0.27452661]
 [0.52781861 0.10260228 0.79066118]
 [0.18547738 0.91515995 0.42936008]
 [0.80653872 0.91546415 0.93381   ]
 [0.61623963 0.35674746 0.15297064]]


In [8]:
## in-place operations
y_pt.add_(x_pt)
print(y_pt)

y_np.__iadd__(x_np)
print(y_np)

tensor([[0.9669, 0.4496, 0.3255],
        [0.2800, 0.9695, 0.9033],
        [0.8509, 0.9402, 0.0901],
        [0.0302, 0.4726, 0.2825],
        [0.6208, 0.3520, 0.2769]])
[[0.81128594 0.7028886  0.27452661]
 [0.52781861 0.10260228 0.79066118]
 [0.18547738 0.91515995 0.42936008]
 [0.80653872 0.91546415 0.93381   ]
 [0.61623963 0.35674746 0.15297064]]


In [9]:
## indexing
print(y_pt[:, 1])
print(y_np[:, 1])

tensor([0.4496, 0.9695, 0.9402, 0.4726, 0.3520])
[0.7028886  0.10260228 0.91515995 0.91546415 0.35674746]


In [10]:
## PyTorch: view
x_pt = torch.randn(4, 4)
y_pt = x_pt.view(16)
z_pt = x_pt.view(-1, 8)
print(x_pt.size(), y_pt.size(), z_pt.size())

## NumPy: reshape
x_np = np.random.randn(4, 4)
y_np = x_np.reshape(16)
z_np = x_np.reshape(-1, 8)
print(x_np.shape, y_np.shape, z_np.shape)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
(4, 4) (16,) (2, 8)


In [11]:
## direct access to the value (not container)
x_pt = torch.randn(1)
print(x_pt) ## with "tensor"
print(x_pt.item())

x_np = np.random.randn(1)
print(x_np) ## with "[]"
print(x_np.item())

tensor([0.1095])
0.1095004677772522
[-0.55731927]
-0.5573192692657932


## PyTorchとNumPy間の変換

- 明示的に言っていないが，２つの種類がある模様．
- 抽出(PyTorchからNumPy)する方法: 後の変化が反映されない (?)
- バインド(NumPyからPyTorch)する方法: 後の変化が反映される

In [12]:
## one-way exporting (PyTorch -> NumPy)
a_pt = torch.ones(5)
print(a_pt)

b_np = a_pt.numpy() ## exporting: just export as NumPy data
print(b_np)

## after exporting, changes in PyTorch does not affect to NumPy data
a_pt = a_pt + a_pt
print(a_pt)
print(b_np)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[1. 1. 1. 1. 1.]


In [13]:
## binding (NumPy-PyTorch)
a_np = np.ones(5)
print(a_np)
b_pt = torch.from_numpy(a_np) ## binding a (NumPy) and b (PyTorch)
print(b_pt)

## after binding, changes in NumPy also transferred to PyTorch
np.add(a_np, 1, out=a_np)
print(a_np)
print(b_pt)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors

- CPU<->GPUや，GPU間の転送に使われる(?)
- まだ完璧でなく，CUDAしか対応できない模様...

In [14]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y_pt = torch.ones_like(x_pt, device=device) ## option (1)
    x_pt = x_pt.to(device)                      ## option (2)
    z_pt = x_pt + y_pt
    print(z_pt)
    print(z_pt.to("cpu", torch.double))         ## send to CPU

tensor([1.1095], device='cuda:0')
tensor([1.1095], dtype=torch.float64)


(end)